#include "SceneManager.h"
#include <algorithm>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <type_traits>
#include <glad/glad.h>
#include <glm/gtc/matrix_inverse.hpp>

namespace {
detail::PrimitiveMesh* Mesh(SceneObjectPayload& p) { return std::visit([](auto& v)->detail::PrimitiveMesh* { using T=std::decay_t<decltype(v)>; if constexpr(std::is_same_v<T,Primitive2D>||std::is_same_v<T,Primitive3D>) return &v; return nullptr; },p); }
const detail::PrimitiveMesh* Mesh(const SceneObjectPayload& p) { return std::visit([](const auto& v)->const detail::PrimitiveMesh* { using T=std::decay_t<decltype(v)>; if constexpr(std::is_same_v<T,Primitive2D>||std::is_same_v<T,Primitive3D>) return &v; return nullptr; },p); }
const char* GeometryName(TerrainGeometryType t){return t==TerrainGeometryType::Flat?"Flat":"Heightmap";}
const char* PlaneName(TerrainPlane p){return p==TerrainPlane::XY?"XY":p==TerrainPlane::YZ?"YZ":"XZ";}
void WriteSceneToken(std::ostream& out,const std::string& value){if(value.empty()||value.find_first_of(" \t\"")!=std::string::npos)out<<std::quoted(value);else out<<value;}
}
SceneManager::SceneManager(){ auto& t=AddTerrain(); std::get<Terrain>(t.payload).SetTexturePath("textures/grass.jpg"); }
SceneObject& SceneManager::AddPrimitive2D(Primitive2DType t,const std::string& x){ auto o=std::make_unique<SceneObject>(t==Primitive2DType::Triangle?"Triangle":"Plane",std::in_place_type<Primitive2D>,t,x); sceneObjects.push_back(std::move(o)); return *sceneObjects.back(); }
SceneObject& SceneManager::AddPrimitive3D(Primitive3DType t,const std::string& x,unsigned a,unsigned b){ auto o=std::make_unique<SceneObject>("Primitive",std::in_place_type<Primitive3D>,t,x,a,b); o->name=std::get<Primitive3D>(o->payload).GetTypeName(); sceneObjects.push_back(std::move(o)); return *sceneObjects.back(); }
SceneObject& SceneManager::AddTerrain(const TerrainConfig& c){ auto o=std::make_unique<SceneObject>("Terrain",std::in_place_type<Terrain>,c); sceneObjects.push_back(std::move(o)); return *sceneObjects.back(); }
SceneObject* SceneManager::GetSkybox(){for(auto& o:sceneObjects)if(std::holds_alternative<Skybox>(o->payload))return o.get();return nullptr;}
const SceneObject* SceneManager::GetSkybox()const{for(auto& o:sceneObjects)if(std::holds_alternative<Skybox>(o->payload))return o.get();return nullptr;}
SceneObject& SceneManager::AddSkybox(const SkyboxConfig& c){if(auto* existing=GetSkybox())return *existing;auto o=std::make_unique<SceneObject>("Skybox",std::in_place_type<Skybox>,c);sceneObjects.push_back(std::move(o));return *sceneObjects.back();}
SceneObject& SceneManager::AddLight(){ auto o=std::make_unique<SceneObject>("Light",std::in_place_type<std::monostate>); o->transform.position={0,1,0}; o->light.emplace(); sceneObjects.push_back(std::move(o)); return *sceneObjects.back(); }
bool SceneManager::RemoveSceneObject(std::size_t i){if(i>=sceneObjects.size())return false;sceneObjects.erase(sceneObjects.begin()+i);return true;}

bool SceneManager::loadScene(const std::string& path){std::ifstream f(path);if(!f)return false;Clear();bool foundTerrain=false;std::string line;while(std::getline(f,line)){if(line.empty()||line[0]=='#')continue;std::istringstream s(line);std::string type,tex;s>>type;float px,py,pz,rx,ry,rz,sx,sy,sz;
 if(type=="Skybox"){SkyboxConfig c;if(!(s>>std::quoted(c.right)>>std::quoted(c.left)>>std::quoted(c.top)>>std::quoted(c.bottom)>>std::quoted(c.front)>>std::quoted(c.back))){std::cerr<<"[SceneManager] Malformed skybox line: "<<line<<'\n';continue;}rx=ry=rz=0.0f;if(s>>rx){if(!(s>>ry>>rz)){std::cerr<<"[SceneManager] Malformed skybox rotation: "<<line<<'\n';continue;}}auto&o=AddSkybox(c);o.transform.rotation={rx,ry,rz};continue;}
 if(type=="Light"){std::string token;s>>token;auto& o=AddLight();float r,g,b;if(token=="Point"||token=="Directional"||token=="Spot"){o.light->type=token=="Spot"?LightType::Spot:token=="Directional"?LightType::Directional:LightType::Point;s>>px>>py>>pz>>rx>>ry>>rz>>r>>g>>b>>o.light->intensity>>o.light->range>>o.light->innerConeAngle>>o.light->outerConeAngle;o.transform.rotation={rx,ry,rz};}else{px=std::stof(token);s>>py>>pz>>r>>g>>b;}o.transform.position={px,py,pz};o.light->color={r,g,b};continue;}
 if(type=="Terrain"){foundTerrain=true;std::string geo,plane,heightmap;s>>geo>>plane>>tex;TerrainConfig c;c.geometryType=geo=="Heightmap"?TerrainGeometryType::Heightmap:TerrainGeometryType::Flat;c.plane=plane=="XY"?TerrainPlane::XY:plane=="YZ"?TerrainPlane::YZ:TerrainPlane::XZ;s>>c.widthSegments>>c.depthSegments>>c.width>>c.depth>>c.heightScale>>px>>py>>pz>>rx>>ry>>rz>>sx>>sy>>sz;auto&o=AddTerrain(c);std::get<Terrain>(o.payload).SetTexturePath(tex);o.transform={{px,py,pz},{rx,ry,rz},{sx,sy,sz}};continue;}
 if(!(s>>tex>>px>>py>>pz>>rx>>ry>>rz>>sx>>sy>>sz))continue;SceneObject* o=nullptr;if(type=="Triangle")o=&AddPrimitive2D(Primitive2DType::Triangle,tex);else if(type=="Plane")o=&AddPrimitive2D(Primitive2DType::Plane,tex);else {auto t=type=="Sphere"?Primitive3DType::Sphere:type=="Slab"?Primitive3DType::Slab:type=="TriangularPrism"?Primitive3DType::TriangularPrism:Primitive3DType::Cube;o=&AddPrimitive3D(t,tex);}o->transform={{px,py,pz},{rx,ry,rz},{sx,sy,sz}};}if(!foundTerrain){auto& defaultTerrain=AddTerrain();std::get<Terrain>(defaultTerrain.payload).SetTexturePath("textures/grass.jpg");}return true;}

bool SceneManager::saveScene(const std::string& path){std::ofstream f(path);if(!f)return false;f<<"# PrimitiveType TexturePath position rotation scale\n# Skybox right left top bottom front back rotation\n# Terrain geometry plane texture segments dimensions heightScale position rotation scale\n# Light legacy or: Light Type position rotation color intensity range innerAngle outerAngle\n";for(auto&op:sceneObjects){auto&o=*op;if(auto*m=Mesh(o.payload)){std::string n=m->GetTypeName();n.erase(std::remove(n.begin(),n.end(),' '),n.end());auto&t=o.transform;f<<n<<' '<<m->GetTexturePath()<<' '<<t.position.x<<' '<<t.position.y<<' '<<t.position.z<<' '<<t.rotation.x<<' '<<t.rotation.y<<' '<<t.rotation.z<<' '<<t.scale.x<<' '<<t.scale.y<<' '<<t.scale.z<<'\n';}else if(auto*t=std::get_if<Terrain>(&o.payload)){auto&c=t->GetConfig();auto&x=o.transform;f<<"Terrain "<<GeometryName(c.geometryType)<<' '<<PlaneName(c.plane)<<' '<<t->GetTexturePath()<<' '<<c.widthSegments<<' '<<c.depthSegments<<' '<<c.width<<' '<<c.depth<<' '<<c.heightScale<<' '<<x.position.x<<' '<<x.position.y<<' '<<x.position.z<<' '<<x.rotation.x<<' '<<x.rotation.y<<' '<<x.rotation.z<<' '<<x.scale.x<<' '<<x.scale.y<<' '<<x.scale.z<<'\n';}else if(auto*sky=std::get_if<Skybox>(&o.payload)){auto&c=sky->GetConfig();auto&r=o.transform.rotation;f<<"Skybox ";WriteSceneToken(f,c.right);f<<' ';WriteSceneToken(f,c.left);f<<' ';WriteSceneToken(f,c.top);f<<' ';WriteSceneToken(f,c.bottom);f<<' ';WriteSceneToken(f,c.front);f<<' ';WriteSceneToken(f,c.back);f<<' '<<r.x<<' '<<r.y<<' '<<r.z<<'\n';}if(o.light){auto&l=*o.light;auto&x=o.transform;const char* type=l.type==LightType::Spot?"Spot":l.type==LightType::Directional?"Directional":"Point";f<<"Light "<<type<<' '<<x.position.x<<' '<<x.position.y<<' '<<x.position.z<<' '<<x.rotation.x<<' '<<x.rotation.y<<' '<<x.rotation.z<<' '<<l.color.r<<' '<<l.color.g<<' '<<l.color.b<<' '<<l.intensity<<' '<<l.range<<' '<<l.innerConeAngle<<' '<<l.outerConeAngle<<'\n';}}return true;}

void SceneManager::drawScene(const Shader&s,const Shader&skyShader,Camera&c,int w,int h){s.Use();s.SetMat4("view",c.GetViewMatrix());s.SetMat4("projection",c.GetProjectionMatrix(w,h));s.SetVec3("viewPos",c.Position);int i=0;for(auto&o:sceneObjects)if(o->enabled&&o->light&&i<10){auto b="lights["+std::to_string(i++)+"]";s.SetVec3(b+".position",o->transform.position);s.SetVec3(b+".color",o->light->color*o->light->intensity);s.SetFloat(b+".shininess",32);}s.SetInt("numLights",i);for(auto&o:sceneObjects){if(!o->enabled||!o->visible||std::holds_alternative<Skybox>(o->payload))continue;s.SetMat4("model",o->transform.Matrix());std::visit([&](auto&v){using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,Primitive2D>||std::is_same_v<T,Primitive3D>){glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,v.GetTextureID());v.draw();}else if constexpr(std::is_same_v<T,Terrain>){glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,v.GetTextureID());v.Draw(s.ID);}},o->payload);}auto* skyObject=GetSkybox();if(!skyObject||!skyObject->enabled||!skyObject->visible)return;auto&sky=std::get<Skybox>(skyObject->payload);if(!sky.IsValid())return;glDepthFunc(GL_LEQUAL);glDepthMask(GL_FALSE);skyShader.Use();skyShader.SetMat4("view",glm::mat4(glm::mat3(c.GetViewMatrix()))*glm::inverse(skyObject->transform.RotationMatrix()));skyShader.SetMat4("projection",c.GetProjectionMatrix(w,h));skyShader.SetInt("skybox",0);glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_CUBE_MAP,sky.GetCubemapID());sky.Draw();glDepthMask(GL_TRUE);glDepthFunc(GL_LESS);}
void SceneManager::DrawLightGizmos(const Shader&s,Camera&c,int w,int h){s.Use();s.SetMat4("view",c.GetViewMatrix());s.SetMat4("projection",c.GetProjectionMatrix(w,h));for(auto&o:sceneObjects)if(o->enabled&&o->light){s.SetMat4("model",glm::scale(glm::translate(glm::mat4(1),o->transform.position),glm::vec3(.1f)));s.SetVec3("lightColor",o->light->color);lightGizmoSphere.draw();}}
bool SceneManager::CheckCollision(const glm::vec3&p,float r,glm::vec3*n){for(auto&o:sceneObjects){if(!o->enabled)continue;if(auto*m=Mesh(o->payload)){m->modelMatrix=o->transform.Matrix();if(m->IntersectsSphere(p,r,n))return true;}else if(auto*t=std::get_if<Terrain>(&o->payload)){if(t->IntersectsSphere(p,r,n,o->transform.Matrix()))return true;}}return false;}
void SceneManager::DrawCollisionMeshes(const Shader&s,const Camera&c,int w,int h,bool primitives,bool terrain){s.Use();s.SetMat4("view",c.GetViewMatrix());s.SetMat4("projection",c.GetProjectionMatrix(w,h));glPolygonMode(GL_FRONT_AND_BACK,GL_LINE);for(auto&o:sceneObjects){s.SetMat4("model",o->transform.Matrix());if(primitives)if(auto*m=Mesh(o->payload))m->drawWireframe();if(terrain)if(auto*t=std::get_if<Terrain>(&o->payload))t->DrawWireframe();}glPolygonMode(GL_FRONT_AND_BACK,GL_FILL);}
